parserOptions:
  ecmaVersion:                        6
  sourceType:                         'module'

rules:
  no-console:                         'off'
  no-param-reassign:
    - 'error'
    - props:                          true
      ignorePropertyModificationsFor:
        - "db"
